// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NRDCL.Customer.Service.DBContexts;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace NRDCL.Customer.Service.Migrations
{
    [DbContext(typeof(CustomerDbContext))]
    [Migration("20210426063444_CustomerInitMigration")]
    partial class CustomerInitMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("NRDCL.Customer.Service.Entities.CustomerEntity", b =>
                {
                    b.Property<string>("CustomerCID")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("MailAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.HasKey("CustomerCID");

                    b.ToTable("CustomerTable");
                });
#pragma warning restore 612, 618
        }
    }
}
